services:
  leaderboard-api:
    image: leaderboard-api:latest
    container_name: leaderboard-api
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - target: 8090
        published: 8090
        protocol: tcp
        mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8090
      - MONGODB_DATABASE_NAME=leaderboard
      - MONGODB_COLLECTION_NAME=records
    secrets:
      - mongo_connection_string
    volumes:
      - ./Leaderboard-API/.env:/app/.env:ro
    networks:
      - leaderboard-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8090/Health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  leaderboard-network:
    driver: overlay
    attachable: true

secrets:
  mongo_connection_string:
    external: true